create schema shop;

create table if not exists shop.product
(
    id    integer generated by default as identity (start with 1 increment by 1) primary key,
    name  varchar(70),
    price integer
);